# Generated by Django 3.2.7 on 2021-09-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
