# Generated by Django 3.2.7 on 2021-09-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0003_alter_shop_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
