# Generated by Django 3.2.7 on 2021-09-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0005_auto_20210930_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='imagetoupload',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
