# Generated by Django 3.2.7 on 2021-09-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0007_alter_shop_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
