# Generated by Django 3.2.7 on 2021-10-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0011_auto_20211001_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
