# Generated by Django 3.2.7 on 2021-10-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0012_rename_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
