# Generated by Django 3.2.7 on 2021-10-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0013_rename_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
